version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - API_KEY=SUA_API_KEY
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    command: mongod --quiet --logpath /dev/null 
